version: '3.1'

name: awantura-o-nauke

services:
    aon-server:
        build:
            context: ../server
            dockerfile: ../docker/server.Dockerfile
        ports:
          - 8001:8001
      
    aon-client:
        environment:
            - VUE_APP_SERVER_ADDRESS=http://awantura-o-nauke.local:8001       
        build:
            context: ../client
            dockerfile: ../docker/client.Dockerfile
        ports:
          - 80:80
        hostname: awantura-o-nauke.local
        volumes:
          - /home/client/node_modules
          - /home/client/build
          - /home/client/dist