version: '3.1'

name: awantura-o-nauke

services:
    aon-server:
        build:
            context: ../server
            dockerfile: ../docker/server.Dockerfile
        ports:
          - 8001:8000
        volumes:
          - ../server:/home/server
          - /home/server/node_modules
      
    aon-client:
        environment:
            - VUE_APP_SERVER_ADDRESS=http://localhost:8001
        build:
            context: ../client
            dockerfile: ../docker/client.Dockerfile
        ports:
          - 8082:8080
        volumes:
          - ../client:/home/client
          - /home/client/node_modules