version: '3.1'

name: awantura-o-nauke

services:
    aon-server:
        build:
            context: ../server
            dockerfile: ../docker/server.Dockerfile
        ports:
            - 8001:8001
        volumes:
            - ../logs/prod:/home/server/logs
      
    aon-client:
        environment:
            - VUE_APP_SERVER_ADDRESS=http://192.168.1.100:8001
        build:
            context: ../client
            dockerfile: ../docker/client.Dockerfile
        ports:
            - 80:80